export const skillset = {
  "Programming Languages": [
    "C",
    "Python",
    "JavaScript",
    "TypeScript",
    "PHP",
    "Dart",
    "SQL",
  ],
  Frontend: [
    "React",
    "Next.js",
    "Flutter",
    "React Native",
    "Bootstrap",
    "TailwindCSS",
    "jQuery",
  ],
  Backend: ["Node.js", "Express", "Laravel"],
  Databases: ["MySQL", "PostgreSQL", "SQLite", "MongoDB", "Redis"],
  "Development Tools": ["Git", "Docker", "Prisma", "Kubernetes", "Webpack"],
  "Cloud Technologies": [
    "Amazon Web Services",
    "Google Cloud Platform",
    "Firebase",
  ],
  "APIs and Web Services": ["REST", "WebSockets"],
  "Currently Learning": ["Django", "GraphQL", "Microservices Architecture"],
};
